import numpy as np
print("Enter the size of the array")
n = int(input())
x = np.random.randint(0,5,n)
print("First array:")
print(x)
y = np.random.randint(0,5,n)
print("Second array:")
print(y)
print("Are the arrays equal?")
check_equality = np.allclose(x, y)
print(check_equality)