import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Are the arrays equal?")
check_equality = np.allclose(x, y)
print(check_equality)